name: Karate Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Download Karate Standalone JAR
      run: |
        curl -L -o karate.jar https://github.com/karatelabs/karate/releases/download/v1.5.0/karate-1.5.0.jar

    - name: Run Karate Tests
      run: |
        java -Dkarate.config=classpath:karate-config.js -jar karate.jar src/test/features/fhir.feature

    # Copy index.html from the site folder to the publish directory
    - name: Prepare GitHub Pages
      run: |
        cp site/index.html target/karate-reports/

    # Upload Karate Reports (assumes reports are generated in target/karate-reports)
    - name: Upload Karate Reports
      uses: actions/upload-artifact@v3
      with:
        name: karate-reports
        path: target/karate-reports/

    # Optional: Deploy reports to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/karate-reports/
