name: Karate Tests

on:
  push:
    branches:
      - main  # Adjust the branch to the one you want to trigger the action on
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Run Karate Tests
      run: mvn test

    - name: Generate Karate Report
      run: mvn exec:java -Dexec.mainClass="com.intuit.karate.Main" -Dexec.args="target/karate-reports" 

    - name: Upload Karate Reports
      uses: actions/upload-artifact@v2
      with:
        name: karate-reports
        path: target/karate-reports/

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/karate-reports
