name: Karate Tests

on:
  push:
    branches:
      - main  # Adjust the branch to the one you want to trigger the action on
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # Use Eclipse Temurin as the JDK distribution
        java-version: '11'

    - name: Build with Maven and Run Karate Tests
      run: mvn test

    - name: Upload Karate Reports
      uses: actions/upload-artifact@v3
      with:
        name: karate-reports
        path: target/karate-reports/

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/karate-reports
